### ISSUE TITLE
코인 관련 질문

### ISSUE THREAD

**Issue by dolphin2410** [w0819/UHC_System#13]
코인이랑 레시피 구매 목록을 데이터베이스에 저장해야 하는데 어떤 데이터베이스가 가장 나을까요?

**Comment by w0819** [comment]
코인은 스코어보드 만들고....

**Comment by w0819** [comment]
코인은 스코어보드 만들어야 하지 않을까요?

**Comment by dolphin2410** [comment]
그럼 레시피는요..?  레시피를 id 형태로 저장해서 스코어보드 쓸까요?

**Comment by w0819** [comment]
스코어보드가 낫지 않을까요?

**Comment by dolphin2410** [comment]
[PersistentDataStorage](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/persistence/PersistentDataContainer.html)로 IntArray를 저장할 수 있네요. 스코어보드의 Int와 String만으로는 한계가 있으니 이로 바꾸는 것은 어떤가요?

**Comment by w0819** [comment]
오 좋을 것 같습니다.

**Comment by dolphin2410** [comment]
#14

**Comment by dolphin2410** [comment]
#14 PR
