### ISSUE TITLE
팀 스폰 이슈

### ISSUE THREAD

**Issue by dolphin2410** [w0819/UHC_System#16]
팀을 랜덤으로 텔레포트하면 가끔 용암같은 것 위에 스폰되는데 어떻게 할까요?

1. 화염저항 주고 그냥 냅둠
2. 직접 코드로 안전한 스폰장소 구현

**Comment by w0819** [comment]
유챔도 초반에 화염 저항 같은 거 주니까 화염 저항을 주는 게 나을 것 같습니다.

**Comment by dolphin2410** [comment]
알겠습니다. 감사합니다.
